name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (no push)
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Save Docker image as artifact
        run: |
          docker save ghcr.io/${{ github.repository }}:latest | gzip > image.tar.gz
        shell: bash

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar.gz

  push-and-gitops:
    runs-on: ubuntu-latest   # GitHub-hosted runner
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: |
          gunzip -c image.tar.gz | docker load

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image
        run: |
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/shaikh4git/k8s-gitops.git gitops
          cd gitops
          
          # Update image tag in deployment.yaml
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          
          # Push
          git push https://${GIT_TOKEN}@github.com/shaikh4git/k8s-gitops.git main
